version: "3.8"

services:
  ezbookkeeping:
    image: ghcr.io/panda-995/ezbookkeeping-pixel:latest
    pull_policy: always
    container_name: ezbookkeeping
    user: 0:0
    ports:
      - "18088:8080"
    volumes:
      - ./data:/ezbookkeeping/data
      - ./storage:/ezbookkeeping/storage
    environment:
      # 开启 API 令牌
      - EBK_SECURITY_ENABLE_API_TOKEN=true
    restart: always
